version: '3.8'

services:
  api:
    platform: linux/amd64
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    command: pnpm --filter api dev

  web:
    platform: linux/amd64
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - API_URL=http://api:4000
    depends_on:
      - api
      - redis
    command: pnpm --filter web dev

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 